version: '3'

services:
  frontend-app:
    image: pokemonreact:latest
    container_name: pokemonwebsite-react
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile

  mongoDb:
    image: mongo
    container_name: pokemonwebsite-mongo
    restart: always
    ports:
    - "27017:27017"

  mongo-seed:
    build: ./backend/mongo-seed
    depends_on:
     - mongoDb

  backend:
    image: pokemonexpress:latest
    container_name: pokemonwebsite-express
    ports:
      - "8080:8080"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile

